repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-yaml
        exclude: ^codespace-like/templates/.*$|^chart-schema.yaml$
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/jtyr/kubeconform-helm
    rev: v0.3.0
    hooks:
      - id: kubeconform-helm
        args: [--strict]
