apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codespace-like.fullname" . }}
  labels:
    {{- include "codespace-like.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "codespace-like.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codespace-like.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "codespace-like.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.docker.enabled }}
        - name: docker
          image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag }}"
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          startupProbe:
            tcpSocket:
              port: 2376
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 2376
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 2376
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.docker.resources | nindent 12 }}
          volumeMounts:
            - name: docker-data
              mountPath: /var/lib/docker
            - name: docker-certs
              mountPath: /certs
            - name: work
              mountPath: /home/coder/work
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
        {{- end }}
        - name: coder
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.docker.enabled }}
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: '1'
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_BUILDKIT
              value: '1'
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: work
              mountPath: /home/coder/work
            {{- if .Values.docker.enabled }}
            - name: docker-certs
              readOnly: true
              mountPath: /certs
            {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.docker.enabled }}
        - name: docker-data
          emptyDir:
            sizeLimit: {{ .Values.docker.volume.sizeLimit }}
        - name: docker-certs
          emptyDir: {}
        {{- end }}
        - name: work
          persistentVolumeClaim:
            claimName: {{ include "codespace-like.fullname" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
