{{- if .Values.persistence.enbaled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codespace-like.fullname" . }}
  labels:
    {{- include "codespace-like.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
