apiVersion: v2
name: helm-chart-codespace-like
description: A Helm chart for deploying a codespace-like dev server
icon: "https://raw.githubusercontent.com/kubernetes/community/master/icons/png/resources/unlabeled/deploy-128.png"
type: application
version: 0.1.4
appVersion: "0.4.0"
maintainers:
  - name: "webofmars"
    email: "contact@webofmars.com"
  - name: "escemi"
    email: "contact@escemi.com"
