---
name: Shared - Continuous Integration for common tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:

  tests-charts:
    name: Tests - Charts
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Test helm charts
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@c9088e8447c5a8be45157e17701023fc50ccb1c0 # 0.37.2
