---
name: Shared - Continuous Integration for common tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:

  tests-charts:
    name: Tests - Charts
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Test helm charts
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@5396e1258d209f9af18e55da8692361508e3338c # 0.36.2
