---
name: Main - Continuous Integration

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      statuses: write
      security-events: write
    secrets: inherit

  helm-docs:
    needs: ci
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: hoverkraft-tech/ci-github-container/actions/helm/generate-docs@5396e1258d209f9af18e55da8692361508e3338c # 0.36.2
        with:
          working-directory: ./codespace-like
          values-file: ./codespace-like/values.yaml
          github-app-id: ${{ vars.CI_BOT_APP_ID }}
          github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
